### ISSUE TITLE
前端界面有关刷新的Bug

### ISSUE THREAD

**Issue by YichenWu11** [wheel-w/bk-c-course#14]
**点击浏览器刷新按钮刷新界面后，导航栏中首页显示为acticve，但页面内容仍为刷新前所在的页面内容**
---
![image](https://user-images.githubusercontent.com/92995653/162420056-9339b54f-42b1-467c-a182-40f88e648b4c.png)

**Comment by light0926** [comment]
简单来说，就是刷新后tab内容和url都不变，但是tab的label变成了"首页"
