### ISSUE TITLE
学生作答答案是否应该支持上传图片

### ISSUE THREAD

**Issue by YichenWu11** [wheel-w/bk-c-course#34]
![image](https://user-images.githubusercontent.com/92995653/163820345-cac9cd40-22dc-40cd-bc09-db00a5528619.png)
### 目前的stu_answers(学生提交答案列表)用JSON格式来保存，不支持学生在提交答案时上传图片。但是很多理工科简答题的答案涉及到大量公式，用纯文本的形式来实现不太现实。

**Comment by wheel-w** [comment]
json里面只存储图片的url
